### ISSUE TITLE
convert_plan.py error

### ISSUE THREAD

**Issue by groot-1313** [NVIDIA-Jetson/tf_to_trt_image_classification#11]
Hi, 

I am using the following command:
`python scripts/convert_plan.py data/frozen_graphs/inception_v1.pb data/plans/inception_v1.plan input 224 224 InceptionV1/Logits/SpatialSqueeze 1 0 float` to convert my network based on the [pix2pix tensorflow model](https://github.com/affinelayer/pix2pix-tensorflow), but I am met with the following error: 

> Using output node generate_output/output
Converting to UFF graph
Warning: No conversion function registered for layer: Cast yet.
Converting as custom op Cast generate_output/output
name: "generate_output/output"
op: "Cast"
input: "generate_output/output/Minimum"
attr {
  key: "DstT"
  value {
    type: DT_UINT8
  }
}
attr {
  key: "SrcT"
  value {
    type: DT_FLOAT
  }
}

Traceback (most recent call last):
  File "scripts/convert_plan.py", line 71, in <module>
    data_type
  File "scripts/convert_plan.py", line 22, in frozenToPlan
    text=False,
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 103, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 75, in from_tensorflow
    name="main")
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 64, in convert_tf2uff_graph
    uff_graph, input_replacements)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 51, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 28, in convert_layer
    fields = cls.parse_tf_attrs(tf_node.attr)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 177, in parse_tf_attrs
    for key, val in attrs.items()}
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 177, in <dictcomp>
    for key, val in attrs.items()}
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 172, in parse_tf_attr_value
    return cls.convert_tf2uff_field(code, val)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 146, in convert_tf2uff_field
    return TensorFlowToUFFConverter.convert_tf2numpy_dtype(val)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 74, in convert_tf2numpy_dtype
    return np.dtype(dt[dtype])
TypeError: list indices must be integers, not AttrValue

I believe it is due to some unsupported layers. Does anyone know of a work around for this?

**Comment by jaybdub-nv** [comment]
It looks like there is no supported TensorRT operation for the TensorFlow operation "Cast".  Potentially there is a way to modify the TensorFlow graph to avoid the unsupported operation, but it is highly dependent on the model architecture.  There is a webinar discussing TensorFlow to TensorRT on Jetson which discusses unsupported operations which may provide some insight

https://devtalk.nvidia.com/default/topic/1030314/jetson-tx2/nvidia-webinar-mdash-tensorflow-to-tensorrt-on-jetson/

**Comment by groot-1313** [comment]
I have managed to change the layers that weren't supported by TensorRT. Now I am facing the following error:

> Using output node generate_output/deprocess/add
Converting to UFF graph
No. nodes: 361
UFF Output written to data/tmp.uff
UFFParser: parsing generate_output/generator/encoder_9/lrelu/mul/x
UFFParser: parsing generate_output/generator/encoder_8/lrelu/mul/x
UFFParser: parsing generate_output/generator/encoder_7/lrelu/mul/x
UFFParser: parsing generate_output/generator/encoder_6/lrelu/mul/x
UFFParser: parsing generate_output/generator/encoder_5/lrelu/mul/x
UFFParser: parsing generate_output/generator/encoder_4/lrelu/mul/x
UFFParser: parsing generate_output/generator/encoder_3/lrelu/mul/x
UFFParser: parsing generate_output/generator/encoder_2/lrelu/mul/x
UFFParser: parsing image_tensor
UFFParser: parsing generate_output/load_images/preprocess/mul/y
UFFParser: parsing generate_output/load_images/preprocess/mul
UFFParser: parsing generate_output/load_images/preprocess/sub/y
UFFParser: parsing generate_output/load_images/preprocess/sub
UFFParser: parsing generate_output/input_images/Reshape/shape
UFFParser: parsing generate_output/input_images/Reshape
UFFParser: parsing generator/encoder_1/conv/filter
UFFParser: parsing generate_output/generator/encoder_1/conv/Conv2D
UFFParser: parsing generate_output/generator/encoder_2/lrelu/mul
UFFParser: parsing generate_output/generator/encoder_2/lrelu/mul_1/x
UFFParser: parsing generate_output/generator/encoder_2/lrelu/Abs
UFFParser: Parser error: generate_output/generator/encoder_2/lrelu/Abs: Unary not supported for other non-constant node
Failed to parse UFF

**Comment by Alexey-Kamenev** [comment]
Not really answering your question, but here is another possible option: if your model has a lot of operations that are not fully supported by UFF and/or TensorRT, you can take a different approach of generating the code (i.e. TensorRT C++/Python API) yourself. In this case you can write the plugins that implement the missing functionality. This is what we do in [NVStereo DNN](https://github.com/NVIDIA-Jetson/redtail/tree/master/stereoDNN) project. Note that it's not exactly easy approach, so it probably should be a last resort.

**Comment by groot-1313** [comment]
@Alexey-Kamenev thanks! I will look into your project if all fails. 

I have managed to replace all unsupported TensorRT operations, but I am stuck dealing with the operations not supported by UFF. This has been an incredibly difficult process, and I am still stuck with quite a few errors. _

**Comment by jaybdub-nv** [comment]
Hi groot-1313.

If you are okay with using the TensorFlow runtime, the recent 1.7 release of TensorFlow supports TensorRT integration.

https://devtalk.nvidia.com/default/topic/1031300/jetson-tx2/tensorflow-1-7-wheel-with-jetpack-3-2-/

The TensorRT package in TensorFlow 1.7 will optimize supported sections of the graph with TensorRT and run the unsupported parts in plain TensorFlow.  I have not tested the build provided in that forum post but it may be worth a shot if you are having difficulty replacing unsupported operations in the graph with supported operations.

If that does not work, or you don't want to use the TensorFlow runtime I may be able to help provided more information about the issues / model, or you could try the method Alexey mentioned.

**Comment by groot-1313** [comment]
Hi @jaybdub-nv , thanks for pointing out the Tensorflow release integrated with TensorRT. Will check it out. 

I am posting my error log here. From what I understand, it doesnt support the `Neg` operation, which in my case involves subtraction. 
I have replaced `1-a` with `1+tf.negative(a)`, `1+(-1*a)`, but the error remains. How can `Neg` not be supported as an operation, since it is such a basic arithmetic operation. The line that causes the error looks like this:
`return (0.5 * (1 + a)) * x + (0.5 * (1 - a)) * tf.abs(x)` 

> Converting to UFF graph
Warning: No conversion function registered for layer: Neg yet.
Converting as custom op Neg generate_output/generator/encoder_2/lrelu/Neg
name: "generate_output/generator/encoder_2/lrelu/Neg"
op: "Neg"
input: "generate_output/generator/encoder_2/lrelu/Identity"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}

Traceback (most recent call last):
  File "scripts/convert_plan.py", line 71, in <module>
    data_type
  File "scripts/convert_plan.py", line 22, in frozenToPlan
    text=False,
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 103, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 75, in from_tensorflow
    name="main")
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 64, in convert_tf2uff_graph
    uff_graph, input_replacements)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 51, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 28, in convert_layer
    fields = cls.parse_tf_attrs(tf_node.attr)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 177, in parse_tf_attrs
    for key, val in attrs.items()}
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 177, in <dictcomp>
    for key, val in attrs.items()}
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 172, in parse_tf_attr_value
    return cls.convert_tf2uff_field(code, val)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 146, in convert_tf2uff_field
    return TensorFlowToUFFConverter.convert_tf2numpy_dtype(val)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 74, in convert_tf2numpy_dtype
    return np.dtype(dt[dtype])
TypeError: list indices must be integers, not AttrValue

**Comment by jaybdub-nv** [comment]
The Neg operation is not supported by TensorRT, but Subtract is supported.  For example, you could implement ``-x`` as

```
x_neg = tf.subtract(x * 0.0, x)
```

Using ``x * 0.0`` instead of just ``0.0`` as the left argument is necessary because TensorRT does not accept a constant as the left argument for the subtract function.  I think this is also the case for other binary operations.  

Also, it also looks like you implement the absolute value of ``x``, as ``tf.maximum(0., x) + tf.maximum(0., -x)``.  Perhaps try

```
tf_x_abs = tf.relu(x) + tf.relu(x_neg)
```

The relu operation is supported, and is equivalent to max(0, x).  Given the above, perhaps the following substitution will work

```
a_neg = tf.subtract(a * 0.0, a)
x_neg = tf.subtract(x * 0.0, x)
return ((a + 1.0) * 0.5) * x + ((a_neg + 1.0) * 0.5) * (tf.nn.relu(x) + tf.nn.relu(x_neg))
```

Maybe there is room for further optimization, but I think the above should succeed.  I hope to hear if this works for your case.

**Comment by groot-1313** [comment]
Hey! That worked for me! Thanks! I have replaced a few other functions, but I am stuck with one more. I think this is the last change to be made. The problem is with the line:
`mean, variance = tf.nn.moments(input, axes=[0, 1, 2], keep_dims=False)`

give the error:
>Converting to UFF graph
Warning: keep_dims is not supported, ignoring...
Warning: No conversion function registered for layer: SquaredDifference yet.
Converting as custom op SquaredDifference generate_output/generator/decoder_2/batchnorm/moments/SquaredDifference
name: "generate_output/generator/decoder_2/batchnorm/moments/SquaredDifference"
op: "SquaredDifference"
input: "generate_output/generator/decoder_2/batchnorm/Identity"
input: "generate_output/generator/decoder_2/batchnorm/moments/StopGradient"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
Traceback (most recent call last):
  File "scripts/convert_plan.py", line 71, in <module>
    data_type
  File "scripts/convert_plan.py", line 22, in frozenToPlan
    text=False,
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 103, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 75, in from_tensorflow
    name="main")
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 64, in convert_tf2uff_graph
    uff_graph, input_replacements)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 51, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 28, in convert_layer
    fields = cls.parse_tf_attrs(tf_node.attr)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 177, in parse_tf_attrs
    for key, val in attrs.items()}
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 177, in <dictcomp>
    for key, val in attrs.items()}
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 172, in parse_tf_attr_value
    return cls.convert_tf2uff_field(code, val)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 146, in convert_tf2uff_field
    return TensorFlowToUFFConverter.convert_tf2numpy_dtype(val)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 74, in convert_tf2numpy_dtype
    return np.dtype(dt[dtype])
TypeError: list indices must be integers, not AttrValue

I replaced it with, Alternate 1:
`mean = tf.reduce_mean(input, axis = [0, 1, 2], keep_dims=False)`
 `devs_squared = tf.multiply(input - mean, input - mean)`
 `variance = tf.reduce_mean(devs_squared, axis = [0, 1, 2], keep_dims=False)`

But it gave me the error:
>UFFParser: Parser error: generate_output/generator/encoder_2/batchnorm/Mean: Reduce operator not supported

I replaced mean with, Alternate 2: 
`mean = tf.keras.backend.sum(input, axis = [0, 1, 2])`
 `div_factor_1 = input.get_shape().as_list()[0]*input.get_shape().as_list()[1]*input.get_shape().as_list()[2]`
`mean = mean * (1 / div_factor_1)`

`devs_squared = tf.multiply(input - mean, input - mean)`
`variance = tf.keras.backend.sum(devs_squared, axis = [0, 1, 2])`
`div_factor_2 = devs_squared.get_shape().as_list()[0]*devs_squared.get_shape().as_list()[1]*devs_squared.get_shape().as_list()[2] `
`variance = variance * (1 / div_factor_2)`

I got the following error:
>UFFParser: Parser error: generate_output/generator/encoder_2/batchnorm/Sum: Reduce operator not supported

I also used `reduce_sum` in alternate 2 instead of `keras.backend.sum`, to meet the same error.
I am hoping this is the last error I have to deal with
