### ISSUE TITLE
Error - While Creating Plan  -convert_plan.py

### ISSUE THREAD

**Issue by sachinhalla** [NVIDIA-Jetson/tf_to_trt_image_classification#12]
Hi,

I  am getting the following error, when I try to create engine with command given.
Also attached is the error log.  Appreciate info/help.
(Using inception_v1.pb)
Command::
python scripts/convert_plan.py data/frozen_graphs/inception_v1.pb data/plans/inception_v1.plan input 224 224 InceptionV1/Logits/SpatialSqueeze 1 0 float

Error:
--------------- Timing InceptionV1/InceptionV1/Conv2d_1a_7x7/Conv2D + InceptionV1/InceptionV1/Conv2d_1a_7x7/Relu(14)
createConstants (243) - Cask Error in ../builder/caskConvolutionTraits.cpp: 0 (initDeviceReservedSpace)
createConstants (243) - Cask Error in ../builder/caskConvolutionTraits.cpp: 0 (initDeviceReservedSpace)

[Error_log.txt](https://github.com/NVIDIA-Jetson/tf_to_trt_image_classification/files/1919063/Error_log.txt)

**Comment by jaybdub-nv** [comment]
Hi Sachinhalla,

Does this issue persist if you restart the Jetson TX2?

**Comment by sachinhalla** [comment]
Hi  jaybdub-nv,

Thank you for your reply.
Actually I am trying to work this out on my laptop with Maxwell based quadro GPU on it.
I have TX2 listed components installed.  Is that fine to work with and optimize/Infer this for gpu on my laptop. Pl let me know.

**Comment by frotms** [comment]
Hi,

    In stage of Convert frozen graph to TensorRT engine:
When I run "python scripts/convert_plan.py data/frozen_graphs/inception_v1.pb data/plans/inception_v1.plan input 224 224 InceptionV1/Logits/SpatialSqueeze 1 0 float",
I got some error:

Traceback (most recent call last):
  File "scripts/convert_plan_lcx.py", line 75, in <module>
    data_type
  File "scripts/convert_plan_lcx.py", line 41, in frozenToPlan
    subprocess.call([UFF_TO_PLAN_EXE_PATH] + args)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

Please help, thank you.

**Comment by frotms** [comment]
Hi,

In stage of Convert frozen graph to TensorRT engine:
When I run "python scripts/convert_plan.py data/frozen_graphs/inception_v1.pb data/plans/inception_v1.plan input 224 224 InceptionV1/Logits/SpatialSqueeze 1 0 float",
I got some error:

Traceback (most recent call last):
File "scripts/convert_plan.py", line 75, in 
data_type
File "scripts/convert_plan.py", line 41, in frozenToPlan
subprocess.call([UFF_TO_PLAN_EXE_PATH] + args)
File "/usr/lib/python3.5/subprocess.py", line 557, in call
with Popen(*popenargs, **kwargs) as p:
File "/usr/lib/python3.5/subprocess.py", line 947, in init
restore_signals, start_new_session)
File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

Please help, thank you.
