### ISSUE TITLE
 raise UffException(str(name) + " was not found in the graph error

### ISSUE THREAD

**Issue by Ambika-Gowda** [NVIDIA-Jetson/tf_to_trt_image_classification#44]
python3 scripts/convert_plan.py data/frozen_graphs/mobilenet_v2.pb data/plans/mobilenet_v2.plan Placeholder 224 224 Softmax 1 0 float
NOTE: UFF has been tested with TensorFlow 1.12.0. Other versions are not guaranteed to work
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.3
=== Automatically deduced input nodes ===
[name: "Placeholder"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: -1
      }
      dim {
        size: 224
      }
      dim {
        size: 224
      }
      dim {
        size: 3
      }
    }
  }
}
]
=========================================

Using output node Softmax
Converting to UFF graph
Traceback (most recent call last):
  File "scripts/convert_plan.py", line 71, in <module>
    data_type
  File "scripts/convert_plan.py", line 22, in frozenToPlan
    text=False,
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 233, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 181, in from_tensorflow
    debug_mode=debug_mode)
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py", line 62, in convert_tf2uff_node
    raise UffException(str(name) + " was not found in the graph. Please use the -l option to list nodes in the graph.")

Please provide soln to this

**Comment by WangFengtu1996** [comment]
Hi, all 
I got a similar error
```
convert pb tp uff
WARNING:tensorflow:From /home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/uff/converters/tensorflow/conversion_helpers.py:274: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

NOTE: UFF has been tested with TensorFlow 1.15.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.9
=== Automatically deduced input nodes ===
[name: "input"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 299
      }
      dim {
        size: 299
      }
      dim {
        size: 3
      }
    }
  }
}
]
=========================================

Using output node [
Using output node P
Using output node r
Using output node e
Using output node d
Using output node i
Using output node c
Using output node t
Using output node i
Using output node o
Using output node n
Using output node s
Using output node ]
Converting to UFF graph
Traceback (most recent call last):
  File "nvidia_xavier_nx_convertor.py", line 200, in <module>
    to.convert()
  File "nvidia_xavier_nx_convertor.py", line 43, in convert
    if not self.tf2uff():
  File "nvidia_xavier_nx_convertor.py", line 60, in tf2uff
    process_result = uff.from_tensorflow_frozen_model(frozen_file = self.input_file, output_nodes = self.output_nodes,preprocessor=None, output_filename = os.path.join(self.output_path, os.path.basename(self.input_file).split('.')[0] + ".uff"))
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/uff/converters/tensorflow/conversion_helpers.py", line 276, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/uff/converters/tensorflow/conversion_helpers.py", line 225, in from_tensorflow
    debug_mode=debug_mode)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/uff/converters/tensorflow/converter.py", line 141, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/uff/converters/tensorflow/converter.py", line 109, in convert_tf2uff_node
    raise UffException(str(name) + " was not found in the graph. Please use the -l option to list nodes in the graph.")
uff.model.exceptions.UffException: ] was not found in the graph. Please use the -l option to list nodes in the graph.
```
